### ISSUE TITLE
No method in multimethod 'select-field' for dispatch value: :field

### ISSUE THREAD

**Issue by Yann-J** [xavierchow/metabase-couchbase-driver#3]
Hello Xavier!

I recently revived my "Metabase on Couchbase" expriments, and unfortunately it looks like things aren't quite working for me any more...

I can connect to my cluster alright (I think), but I keep getting errors when scanning my bucket schema...

The error I'm getting in the logs is:

```
[bba1a421-a71c-4d8f-9d88-e7e41f9a66de] 2021-05-31T12:50:45+02:00 INFO metabase.sync.util STARTING: step 'fingerprint-fields' for couchbase Database 3 'Duma'
[bba1a421-a71c-4d8f-9d88-e7e41f9a66de] 2021-05-31T12:50:45+02:00 INFO metabase.sync.analyze fingerprint-fields Analyzed [************······································] 😒   25% Table 6 'type:VerticalRepayment.repayments'
[bba1a421-a71c-4d8f-9d88-e7e41f9a66de] 2021-05-31T12:50:45+02:00 INFO metabase.driver.couchbase mbql->native query {:database 3, :type :query, :query {:source-table 6, :fields [[:field 60 nil] [:field 61 nil] [:field 62 nil] [:field 63 nil] [:field 64 nil] [:field 65 nil] [:field 66 nil] [:field 67 nil] [:field 68 nil] [:field 69 nil] [:field 70 nil] [:field 71 nil] [:field 72 nil] [:field 73 nil] [:field 74 nil] [:field 75 nil] [:field 76 nil] [:field 77 nil] [:field 78 nil] [:field 79 nil] [:field 80 nil] [:field 81 nil] [:field 82 nil]], :limit 10000}, :middleware {:format-rows? false, :skip-results-metadata? true}}
[bba1a421-a71c-4d8f-9d88-e7e41f9a66de] 2021-05-31T12:50:45+02:00 WARN metabase.sync.util Error fingerprinting Table 6 'type:VerticalRepayment.repayments'
java.lang.IllegalArgumentException: No method in multimethod 'select-field' for dispatch value: :field
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.core$map$fn__5866.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5866.invoke(core.clj:2746)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.LazySeq.first(LazySeq.java:73)
	at clojure.lang.RT.first(RT.java:692)
	at clojure.core$first__5384.invokeStatic(core.clj:55)
	at clojure.string$join.invokeStatic(string.clj:180)
	at clojure.string$join.invoke(string.clj:180)
	at metabase.driver.couchbase.query_processor$fn__583.invokeStatic(query_processor.clj:131)
	at metabase.driver.couchbase.query_processor$fn__583.invoke(query_processor.clj:126)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.couchbase.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:156)
	at metabase.driver.couchbase.query_processor$mbql__GT_native.invoke(query_processor.clj:149)
	at metabase.driver.couchbase$fn__943.invokeStatic(couchbase.clj:76)
	at metabase.driver.couchbase$fn__943.invoke(couchbase.clj:72)
...
```

My table definition is as follows (although I've tried a few variants):

```
{"tables": [
  {"name": "repayments", "schema": "type:VerticalRepayment", "fields":[
    { "name": "repaymentID", "type": "Text","database-position": 0, "pk?": true},
    { "name": "seasonName", "type": "Text","database-position": 1 },
    { "name": "countryName", "type": "Text","database-position": 2 },
    { "name": "countryCode", "type": "Text","database-position": 3 },
    { "name": "regionName", "type": "Text","database-position": 4 },
    { "name": "districtName", "type":"Text", "database-position": 5 },
    { "name": "sectorName", "type":"Text", "database-position": 6 },
    { "name": "siteName", "type":"Text", "database-position": 7 },
    { "name": "groupName", "type":"Text", "database-position": 8 },
    { "name": "siteNameOriginal", "type":"Text", "database-position": 9 },
    { "name": "groupNameOriginal", "type":"Text", "database-position": 10 },
    { "name": "clientFirstName", "type":"Text", "database-position": 11 },
    { "name": "clientLastName", "type":"Text", "database-position": 12 },
    { "name": "clientAccountNumber", "type":"Text", "database-position": 13 },
    { "name": "globalClientID", "type":"Text", "database-position": 14 },
    { "name": "currencyCode", "type":"Text", "database-position": 15 },
    { "name": "receiptID", "type":"Text", "database-position": 16 },
    { "name": "repaymentType", "type":"Text", "database-position": 17 },
    { "name": "repaymentDate", "type":"Text", "database-position": 18 },
    { "name": "repaymentPhoneNumber", "type":"Text", "database-position": 19 },
    { "name": "amount", "base-type": "Float","database-position": 20 },
    { "name": "dropped", "base-type": "Boolean","database-position": 21 },
    { "name": "autosaved", "base-type": "Boolean","database-position": 22 },
    { "name": "repaymentDate", "base-type": "DateTime","database-position": 23 }
  ]}
]}
```

Am I doing something wrong? I remember I had made it work a few months back...

Thanks for the help!

**Comment by xavierchow** [comment]
@Yann-J 
hmm, I didn't expect a mbql with `[:fields [[:field 60 nil] ... ]]` when doing the fingerprint-fields, which Metabase version are you running with?

I tried your schema without issue with metabase v0.37.2.

```
2021-06-01 22:17:02,137 INFO driver.couchbase :: describe-database:  {:dbname "article", :host "localhost", :user "Administrator", :password "password", :definitions "{\"tables\": [   {\"name\": \"repayments\", \"schema\": \"type:VerticalRepayment\", \"fields\":[     { \"name\": \"repaymentID\", \"type\": \"Text\",\"database-position\": 0, \"pk?\": true},     { \"name\": \"seasonName\", \"type\": \"Text\",\"database-position\": 1 },     { \"name\": \"countryName\", \"type\": \"Text\",\"database-position\": 2 },     { \"name\": \"countryCode\", \"type\": \"Text\",\"database-position\": 3 },     { \"name\": \"regionName\", \"type\": \"Text\",\"database-position\": 4 },     { \"name\": \"districtName\", \"type\":\"Text\", \"database-position\": 5 },     { \"name\": \"sectorName\", \"type\":\"Text\", \"database-position\": 6 },     { \"name\": \"siteName\", \"type\":\"Text\", \"database-position\": 7 },     { \"name\": \"groupName\", \"type\":\"Text\", \"database-position\": 8 },     { \"name\": \"siteNameOriginal\", \"type\":\"Text\", \"database-position\": 9 },     { \"name\": \"groupNameOriginal\", \"type\":\"Text\", \"database-position\": 10 },     { \"name\": \"clientFirstName\", \"type\":\"Text\", \"database-position\": 11 },     { \"name\": \"clientLastName\", \"type\":\"Text\", \"database-position\": 12 },     { \"name\": \"clientAccountNumber\", \"type\":\"Text\", \"database-position\": 13 },     { \"name\": \"globalClientID\", \"type\":\"Text\", \"database-position\": 14 },     { \"name\": \"currencyCode\", \"type\":\"Text\", \"database-position\": 15 },     { \"name\": \"receiptID\", \"type\":\"Text\", \"database-position\": 16 },     { \"name\": \"repaymentType\", \"type\":\"Text\", \"database-position\": 17 },     { \"name\": \"repaymentDate\", \"type\":\"Text\", \"database-position\": 18 },     { \"name\": \"repaymentPhoneNumber\", \"type\":\"Text\", \"database-position\": 19 },     { \"name\": \"amount\", \"base-type\": \"Float\",\"database-position\": 20 },     { \"name\": \"dropped\", \"base-type\": \"Boolean\",\"database-position\": 21 },     { \"name\": \"autosaved\", \"base-type\": \"Boolean\",\"database-position\": 22 },     { \"name\": \"repaymentDate\", \"base-type\": \"DateTime\",\"database-position\": 23 }   ]} ]}"}
2021-06-01 22:17:02,172 INFO sync.util :: FINISHED: step 'sync-metabase-metadata' for couchbase Database 6 'article' (37.3 ms)
2021-06-01 22:17:02,230 INFO sync.util :: FINISHED: Sync metadata for couchbase Database 6 'article' (200.2 ms)
2021-06-01 22:17:02,232 INFO sync.util :: STARTING: Analyze data for couchbase Database 6 'article'
2021-06-01 22:17:02,236 INFO sync.util :: STARTING: step 'fingerprint-fields' for couchbase Database 6 'article'
2021-06-01 22:17:02,251 INFO sync.analyze :: fingerprint-fields Analyzed [************······································] 😒   25% Table 15 'type:VerticalRepayment.repayments'
2021-06-01 22:17:02,252 INFO sync.util :: FINISHED: step 'fingerprint-fields' for couchbase Database 6 'article' (15.4 ms)
2021-06-01 22:17:02,252 INFO sync.util :: STARTING: step 'classify-fields' for couchbase Database 6 'article'
2021-06-01 22:17:02,256 INFO sync.analyze :: classify-fields Analyzed [*************************·························] 😬   50% Table 15 'type:VerticalRepayment.repayments'
2021-06-01 22:17:02,257 INFO sync.util :: FINISHED: step 'classify-fields' for couchbase Database 6 'article' (4.3 ms)
2021-06-01 22:17:02,257 INFO sync.util :: STARTING: step 'classify-tables' for couchbase Database 6 'article'
2021-06-01 22:17:02,269 INFO sync.analyze :: classify-tables Analyzed [*************************************·············] 😋   75% Table 15 'type:VerticalRepayment.repayments'
2021-06-01 22:17:02,270 INFO sync.util :: FINISHED: step 'classify-tables' for couchbase Database 6 'article' (12.4 ms)
2021-06-01 22:17:02,280 INFO sync.util :: FINISHED: Analyze data for couchbase Database 6 'article' (48.3 ms)
```

**Comment by Yann-J** [comment]
Thanks for getting back!

I'm using the `metabase/metabase:latest` image, which is apparently v0.39.3 right now...

**Comment by Yann-J** [comment]
Yes I confirm it's working on `v0.37` indeed for me as well so it must be some regression in metabase... The problem is that I cannot downgrade apparently (the db migration scripts won't let me). I had to test this on a fresh instance...

**Comment by xavierchow** [comment]
@Yann-J no worry, I will try to upgrade this driver to support the mbql change for v0.39 soon

**Comment by xavierchow** [comment]
@Yann-J pls try to use https://github.com/xavierchow/metabase-couchbase-driver/releases/tag/v1.0.6 with v0.39.3, 
let me know if you have any other issues.

**Comment by Yann-J** [comment]
Hmm thanks @xavierchow but unfortunately no luck... but it's a different error this time so it might have to do with my how my bucket is made up? I don't fully understand the stack trace...

```
[265c88a1-165e-447c-b402-95b2121ef6c5] 2021-06-06T17:52:38+02:00 INFO metabase.driver.couchbase mbql->native query {:constraints {:max-results 10000, :max-results-bare-rows 2000}, :type :query, :middleware {:js-int-to-string? true}, :info {:executed-by 1, :context :question, :card-id 1, :query-hash #object["[B" 0x4e8134df "[B@4e8134df"]}, :database 3, :query {:source-table 6, :aggregation [[:aggregation-options [:sum [:field 66 nil]] {:name "sum"}]], :breakout [[:field 63 nil]], :order-by [[:asc [:field 63 nil]]]}, :async? true}
[265c88a1-165e-447c-b402-95b2121ef6c5] 2021-06-06T17:52:39+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: null
{:database_id 3,
 :started_at #t "2021-06-06T15:52:38.948142Z[GMT]",
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :database 3,
  :query {:source-table 6, :aggregation [[:sum [:field 66 nil]]], :breakout [[:field 63 nil]]},
  :parameters [],
  :async? true,
  :cache-ttl nil},
 :native nil,
 :status :failed,
 :class java.lang.IllegalStateException,
 :stacktrace
 ["clojure.lang.Var$Unbound.throwArity(Var.java:45)"
  "clojure.lang.AFn.invoke(AFn.java:40)"
  "--> driver.couchbase.query_processor$fn__858$match_859__860.invoke(query_processor.clj:147)"
  "driver.couchbase.query_processor$fn__858.invokeStatic(query_processor.clj:147)"
  "driver.couchbase.query_processor$fn__858.invoke(query_processor.clj:144)"
  "driver.couchbase.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:162)"
  "driver.couchbase.query_processor$mbql__GT_native.invoke(query_processor.clj:155)"
  "driver.couchbase$fn__950.invokeStatic(couchbase.clj:76)"
  "driver.couchbase$fn__950.invoke(couchbase.clj:72)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:14)"
  "query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:9)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47511.invoke(mbql_to_native.clj:22)"
  "query_processor.middleware.check_features$check_features$fn__46625.invoke(check_features.clj:39)"
  "query_processor.middleware.limit$limit$fn__47497.invoke(limit.clj:37)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__46077.invoke(cache.clj:211)"
  "query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47757.invoke(optimize_temporal_filters.clj:204)"
  "query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49687.invoke(validate_temporal_bucketing.clj:50)"
  "query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45196.invoke(auto_parse_filter_values.clj:43)"
  "query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41497.invoke(wrap_value_literals.clj:161)"
  "query_processor.middleware.annotate$add_column_info$fn__41372.invoke(annotate.clj:605)"
  "query_processor.middleware.permissions$check_query_permissions$fn__46497.invoke(permissions.clj:81)"
  "query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48615.invoke(pre_alias_aggregations.clj:40)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46698.invoke(cumulative_aggregations.clj:60)"
  "query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48914.invoke(resolve_joined_fields.clj:102)"
  "query_processor.middleware.resolve_joins$resolve_joins$fn__49227.invoke(resolve_joins.clj:171)"
  "query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44772.invoke(add_implicit_joins.clj:190)"
  "query_processor.middleware.large_int_id$convert_id_to_string$fn__47461.invoke(large_int_id.clj:59)"
  "query_processor.middleware.format_rows$format_rows$fn__47442.invoke(format_rows.clj:74)"
  "query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__44066.invoke(add_default_temporal_unit.clj:23)"
  "query_processor.middleware.desugar$desugar$fn__46764.invoke(desugar.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__45583.invoke(binning.clj:227)"
  "query_processor.middleware.resolve_fields$resolve_fields$fn__46300.invoke(resolve_fields.clj:34)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__44421.invoke(add_dimension_projections.clj:314)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44650.invoke(add_implicit_clauses.clj:147)"
  "query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49636.invoke(upgrade_field_literals.clj:40)"
  "query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44935.invoke(add_source_metadata.clj:123)"
  "query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48789.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)"
  "query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45143.invoke(auto_bucket_datetimes.clj:147)"
  "query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46347.invoke(resolve_source_table.clj:45)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48597.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46399.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47148.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__44944.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49589.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800$fn__48804.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48800.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47388.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__49598$fn__49599.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49598.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__49643.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47524.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44790.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49574.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__46641.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__48686.invoke(process_userland_query.clj:135)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46581.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38051$thunk__38052.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38051$fn__38054.invoke(reducible.clj:108)"],
 :context :question,
 :error "Attempting to call unbound fn: #'metabase.mbql.util.match/match-in-collection",
 :row_count 0,
 :running_time 0,
 :preprocessed
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true},
  :info
  {:executed-by 1,
   :context :question,
   :card-id 1,
   :query-hash
   [33, -12, -92, 116, 56, -65, 14, -85, 73, 68, 1, 112, 49, -7, 116, -87, -39, 95, 97, 124, 105, -108, -94, 118, 33,
    -32, 38, 98, 45, -86, -117, -89]},
  :database 3,
  :query
  {:source-table 6,
   :aggregation [[:aggregation-options [:sum [:field 66 nil]] {:name "sum"}]],
   :breakout [[:field 63 nil]],
   :order-by [[:asc [:field 63 nil]]]},
  :async? true},
 :data {:rows [], :cols []}}
```

**Comment by Yann-J** [comment]
OK, I'm not sure what was wrong, but after a clean install, everything actually looks fine now! Thanks for the quick fix!
